version: '3'
services:
  web:
    build: .docker/web/
    command: sh -c "cd /wp && php -S 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/wp
    depends_on:
      - db
    environment:
      WP_DB_NAME: wp
      WP_DB_USER: root
      WP_DB_PASSWORD: password
      WP_DB_HOST: db
      TZ: Asia/Tokyo
  db:
    image: mysql:5.7
    command: mysqld
    volumes:
      - db-data:/var/lib/mysql
      - ./config/db/development:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
  webpack:
    image: node:8.11-alpine
    command: sh -c "cd /wp/wp-content/themes/${THEME_NAME} && (yarn check || yarn install) && yarn run webpack-dev-server --progress --color --config /wp/wp-content/themes/${THEME_NAME}/config/webpack/development.js"
    volumes:
      - ./wp-content/themes/${THEME_NAME}:/wp/wp-content/themes/${THEME_NAME}
    ports:
      - 8080:8080
    environment:
      TZ: Asia/Tokyo
      NODE_ENV: development
volumes:
  db-data:
