# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: assets/
  source_entry_path: ''
  public_output_path: dist
  cache_path: tmp/cache/webpacker

  extensions:
    - .coffee
    - .erb
    - .js
    - .jsx
    - .ts
    - .vue
    - .sass
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg
    - .tag
    - .pug
    - .vue

development:
  <<: *default

  compile: false

  dev_server:
    host: 0.0.0.0
    port: 8080
    https: false

staging:
  <<: *default
  compile: false
  cache_manifest: true

production:
  <<: *default
  compile: false
  cache_manifest: true
